### ISSUE TITLE
Implement a data catalog system for existing CCAO data architecture

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#10]
## Goal

Design and implement a data catalog system for internal use that improves our data documentation, quality, and orchestration.

## Overview

The Data Department currently has an extremely ad-hoc and incomplete data catalog system, spread out over multiple spreadsheets and services. We should consolidate these efforts into a single place or platform to serve as a "source of truth" for our department. Ideally, the catalog should provide (in descending rank order of priority):

- Schema / referential integrity validation between linked tables
- Data quality and integrity metrics, see #15 
- Pipeline orchestration and scheduling + validation
- Some insight into data sourcing and lineage (what changed, when, etc.)
- Documentation about tables, columns, and relationships (metadata, notes, etc.)

## Problems to solve

See "Initial Issues" in the draft architecture project overview [here](https://github.com/orgs/ccao-data/projects/11/views/1?pane=info). 

## Possible solutions

This seems like an area where lots of good software solutions already exist, since these needs are common across organizations. The two I've looked at are [DBT](https://www.getdbt.com/) and [Glue](https://aws.amazon.com/glue/), both of which could likely meet the needs provided above. However, I'm sure there are plenty of other possible solutions.

@jeancochrane

**Comment by jeancochrane** [comment]
I'm going to start this effort with a design doc proposing how the catalog should work.

**Comment by dfsnow** [comment]
Perfect! We can work together to flesh out exactly what it will look like, what tasks will need to be done, etc. Let's use this issue as the overarching project and create sub-issues as needed.

**Comment by jeancochrane** [comment]
The design doc is up for review in https://github.com/ccao-data/data-architecture/pull/22 and issues have been created in this milestone: https://github.com/ccao-data/data-architecture/milestone/1 @dfsnow Do you think we still need this issue, or can we let the milestone supersede it?

**Comment by dfsnow** [comment]
@jeancochrane Let's keep this open as the overall tracking issue since I don't believe milestones can be added in GH Projects. I wanted to add this to the overall Data Department planning project.

**Comment by dfsnow** [comment]
@jeancochrane I'm going to call this closed. I'm moving any remaining issues covered by this to https://github.com/ccao-data/data-architecture/milestone/2.
