### ISSUE TITLE
[Data catalog] Fix `cleanup-dbt-resources` workflow so it doesn't error in case of deferral

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#104]
As of https://github.com/ccao-data/data-architecture/pull/90, we are now properly saving and restoring the dbt cache in the context of the `build-and-test-dbt` workflow. Since we use [the `--defer` flag](https://docs.getdbt.com/reference/node-selection/defer) in cases of a cache hit, we now expect to rarely build models on CI; per the behavior of `--defer` with the `state:modified` and `state:new` state options, models should only be built if they have been added or modified, and otherwise CI will fall back to upstream instantiations of those models.

One side effect of this behavior is that our assumption in the `cleanup-dbt-resources` workflow that every schema in the project has been built is no longer true; see for example [this workflow run](https://github.com/ccao-data/data-architecture/actions/runs/6026176207/job/16348510525#step:5:1) which errored when trying to delete schemas that had not been built during the PR. We need to update this workflow to accommodate the fact that we now expect many if not most schemas to not be built in the majority of CI runs.

**Comment by jeancochrane** [comment]
Hm, seems like [the workflow run](https://github.com/ccao-data/data-architecture/actions/runs/6039297429/job/16387616764) didn't actually succeed... reopening this!

**Comment by dfsnow** [comment]
@jeancochrane Is this now closed by #106?

**Comment by jeancochrane** [comment]
Yup, good catch @dfsnow! Closing.
