### ISSUE TITLE
Fix hard boundaries in airport noise surface

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#107]
Previously, the Data Department created an airport noise feature based on kriging the noise values recorded from ground-based sensors. This approach created a continuous surface showing airport noise, with a fallback value for PINs not covered by the surface. The "surface" covers most of Chicago and Cook, but purposefully does not cover _all_ of Cook (it was limited due to computational expense).

However, per @mbjackson-capp, this implementation may have some strange effects, as there is a discontinuity in the noise values when moving from the edge of the surface to the fallback value.

We should either:

- Update the airport noise feature to use a kriging surface that covers all parcels in Cook County (no need for a fallback value)
- Replace the feature with a simpler model based on the physical falloff of noise ` 1 / r^2 ` (inverse square)

**Comment by stevevance** [comment]
The Chicago Department of Aviation has a program to replace windows in houses affected by noise. I presume they have geographic standards as to which houses are eligible. Would this be an alternative to using the "surface"?
