### ISSUE TITLE
[Data catalog] Create a view/CTAS issue template

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#108]
Now that dbt is set up, we should create a brief issue template that includes the steps necessary to create or modify a dbt model. This list would include (not exhaustively):

- Where/how to symlink into the dbt models dir
- Where/how to update the schema files for new views/models
- How to pick the appropriate materialization given our data
- Where to add tests, what to test, testing requirements for new views, etc.

**Comment by jeancochrane** [comment]
Closed by https://github.com/ccao-data/data-architecture/pull/117.
