### ISSUE TITLE
[Data catalog] Write a dispatchable workflow for rebuilding models

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#128]
Per [this PR comment thread](https://github.com/ccao-data/data-architecture/pull/111#issuecomment-17160958250), we need a way to rebuild our output models when their source data change, e.g. when we rerun our R extraction scripts once per year. We could theoretically do this by running one-off `dbt run` commands locally, but that would require downloading and then reuploading the remote master state in a way that is risky and fragile. There are a number of automated ways we could accomplish the same goal (see the PR comment thread for some discussion), but the fastest and most reliable will be to just define a new GitHub Action workflow that takes a list of selectors as input and uses them to build the selected models.

Workflow requirements:

* Is named `build-dbt-models` and stored in `.github/workflows/build_dbt_models.py`
* Can be [dispatched manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#configuring-a-workflow-to-run-manually) (see [`test-dbt-models`](https://github.com/ccao-data/data-architecture/blob/21b40aa4e4e38dceadac6db8d30d9140c36a0385/.github/workflows/test_dbt_models.yaml#L3) for an example of this)
* Accepts a list of strings as an [input variable](https://medium.com/@geralexgr/parameters-and-variables-github-workflows-8bc86b641a4b), where each string represents a symbol that can be passed to a [dbt `--select` option](https://docs.getdbt.com/reference/node-selection/syntax#specifying-resources)
* Has the same [checkout, setup, and remote state download behavior](https://github.com/ccao-data/data-architecture/blob/21b40aa4e4e38dceadac6db8d30d9140c36a0385/.github/workflows/build_and_test_dbt.yaml#L9-L32) as `build-and-test-dbt`
* Runs the build via `dbt run -t "$TARGET" -s <state selectors based on input variables> --defer --state "$STATE_DIR"` after downloading remote state
* [Updates the dbt cache](https://github.com/ccao-data/data-architecture/blob/21b40aa4e4e38dceadac6db8d30d9140c36a0385/.github/workflows/build_and_test_dbt.yaml#L73-L77) in the same fashion as `build-and-test-dbt` if the build succeeds

**Comment by dfsnow** [comment]
@jeancochrane How do you feel about me just editing `build_and_test_dbt.yaml` instead of adding a new workflow. Almost all of the requirements here are already met by that workflow except the input string and manual dispatch.

**Comment by dfsnow** [comment]
Also, let's take this as an opportunity to replace the `reporting-res_report_summary` Glue job.

**Comment by jeancochrane** [comment]
> How do you feel about me just editing build_and_test_dbt.yaml instead of adding a new workflow. Almost all of the requirements here are already met by that workflow except the input string and manual dispatch. Just want to confirm this isn't a terrible idea before I get started.

In hindsight that seems like the obvious choice, good thinking @dfsnow! Let's go for it 👍🏻
