### ISSUE TITLE
Update internal views

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#14]
Was looking through the views when I was linting things a few weeks back and found a few to-dos:

- [ ] The `values_by_year` CTE in vw_assessment_roll can be replaced with the equivalent view
- [ ] The `values_by_year` CTE in vw_top_5 can be replaced with the equivalent view
- [ ] The res model view needs to be updated with proper filling + linted with SQLfluff
- [ ] Same as above for the condo model view

**Comment by wrridgeway** [comment]
model views linted, vw_top_5 view now uses default.vw_pin_value, but vw_pin_value _cannot_ be swapped into vw_assessment_roll

**Comment by wrridgeway** [comment]
Gonna close for now. Can reopen if it turns out these issues haven't been sufficiently addressed.
