### ISSUE TITLE
[Data catalog] Revamp process for updating feature documentation in res model README

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#140]
By factoring out the lineage/description fields from the vars dict in the `ccao` package (https://github.com/ccao-data/ccao/issues/2), we ended up breaking an assumption of the res model README, which [relies on](https://github.com/ccao-data/model-res-avm/blob/d1144b882c0e94ed0b9a185031f08bcc94ec25c7/README.Rmd#L220) `var_is_predictor` and `var_notes` in particular to knit together a table with information on the model features.

Now that these attributes have been removed from the vars dict in the `ccao` package, we need to come up with some sort of way of populating this table that doesn't rely on the vars dict. We'll likely want to extract that information from the dbt docs, hence this issue being opened against the `data-architecture` repo instead of the `model-res-avm` repo. One possible solution would be to A) add an `is_predictor` field to the `config.meta` schema attribute for each feature column and B) use that field to pull out predictor features from the dbt manifest and parse their `description` attributes, but I expect there may be unforeseen challenges with that approach.

**Comment by jeancochrane** [comment]
The res model README is done in https://github.com/ccao-data/model-res-avm/pull/18! Next up is the [condo model README](https://github.com/ccao-data/model-condo-avm/).

**Comment by dfsnow** [comment]
@jeancochrane Is this all set to be closed?

**Comment by jeancochrane** [comment]
Yup, thanks @dfsnow! Closed by https://github.com/ccao-data/model-condo-avm/pull/4.
