### ISSUE TITLE
Remove common area as criteria for nonlivable in condo model view

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#152]
Valuations believes we should treat historical common areas as normal condo units/parking spaces for modeling and let their validity be determined through the appeal process. We should remove common areas as a criteria for the `nonlivable` modeling group.

**Comment by stevevance** [comment]
are you referring to the shared driveways that are common in many townhouse developments?

The map shows a few shared driveways at townhouse developments in Chicago's West Loop, which are classified as `1-00` (vacant land):
![image](https://github.com/ccao-data/data-architecture/assets/1330459/0fdd1ae1-da0a-45d4-bf04-029c839bd152)

My suggestion to CCAO is to develop additional property classes for "infrastructure" parcels. I have developed an alternative dataset for infrastructure parcels so they are hidden by default when people look on Chicago Cityscape for vacant land.
