### ISSUE TITLE
Model infrastructure improvements

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#175]
- [x] https://github.com/ccao-data/model-res-avm/issues/22
- [x] https://github.com/ccao-data/model-res-avm/issues/23
- [x] https://github.com/ccao-data/model-res-avm/issues/24
- [x] https://github.com/ccao-data/model-condo-avm/issues/5
- [x] https://github.com/ccao-data/model-res-avm/issues/56
- [x] https://github.com/ccao-data/model-res-avm/issues/57

**Comment by jeancochrane** [comment]
@dfsnow OK if I close this? We haven't added a performance report to the condo model but I'm not sure if we want to be tracking that work yet.

**Comment by dfsnow** [comment]
Closed!
