### ISSUE TITLE
Gather 2023 existing data for 2024 modeling

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#21]
Collect res and condo third-party data (spatial data, environmental data, etc). Update the ingest scripts in `aws-s3` directory.

**Comment by wrridgeway** [comment]
Data refresh is nearing completion. At this point all that's left are datasets we're owed by valuations (condo characteristics for the city, land rates), and data it behooves us to wait as long as possible to gather, namely MyDec sales from IDOR and foreclosures.

See the [update inventory](https://github.com/ccao-data/data-architecture/blob/21-gather-2023-existing-data-for-2024-modeling/aws-s3/update_inventory.xlsx) for details.

**Comment by dfsnow** [comment]
@wrridgeway Now that sales are in, we're only waiting on condo data now, yes?

**Comment by wrridgeway** [comment]
yep
