### ISSUE TITLE
Materialize model views

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#232]
Our `model` views are heavy and cause queries to take a long time to execute. To speed up model iteration, we should materialize these views to improve runtime performance. If we do this by adding the `daily` tag to their schema file definitions we can ensure that they get materialized once per day, which should be enough to ensure we're staying up to date with changes to ias.

CC @dfsnow

**Comment by dfsnow** [comment]
One additional to-do for this: let's add row count tests to these views as seen in #246.
