### ISSUE TITLE
Add new airport noise feature to proximity, model views

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#235]
Now that #231 is merged, we also need to add the resulting feature to the views that actually feed the models. This involves updating the SQL for the following views:

- `proximity.vw_pin10_proximity`
- `proximity.crosswalk_year_fill`
- `proximity.vw_pin10_proximity_fill`
- `model.vw_pin_shared_input`
- `model.vw_card_res_input`
- `model.vw_pin_condo_input`

The features in most of these views are alphabetical, so `airport_dnl_total` should go before the bike trail features in most of these views. Most of these should be fairly small edits to just a couple lines. We'll also need to update the dbt documentation for each view and the relevant Open Data asset ([Parcel proximity](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Parcel-Proximity/ydue-e5u3), ping @wrridgeway for this).

**Comment by mbjackson-capp** [comment]
Checklist for tracking progress

- [ ] proximity.vw_pin10_proximity
    - [ ] update SQL
    - [ ] update dbt documentation
- [ ] proximity.crosswalk_year_fill
    - [ ] update SQL
    - [ ] update dbt documentation
- [ ] proximity.vw_pin10_proximity_fill
    - [ ] update SQL
    - [ ] update dbt documentation
- [ ] model.vw_pin_shared_input
    - [ ] update SQL
    - [ ] update dbt documentation
- [ ] model.vw_card_res_input
    - [ ] update SQL
    - [ ] update dbt documentation
- [ ] model.vw_pin_condo_input
    - [ ] update SQL
    - [ ] update dbt documentation

- [ ] update Open Data documentation

**Comment by wrridgeway** [comment]
![image](https://github.com/ccao-data/data-architecture/assets/10358980/1911c85b-e958-4219-b68d-5dc8f76ed879)
