### ISSUE TITLE
Add commercial incentive class CDU to `vw_pin_universe` + Open Data

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#240]
A third-party has requested that incentive property CDU codes be added Open Data. See bottom of the [class code list](https://prodassets.cookcountyassessor.com/s3fs-public/form_documents/classcode.pdf) for examples.

To make this happen, we need to update `default.vw_pin_universe` with the proper `COMDAT` CDU fields. The correct field is either: `comdat.cdu` or `comdat.user16`, per Will C.

Let's add this field to the view then refresh Open Data.

**Comment by wrridgeway** [comment]
move to https://github.com/ccao-data/public/issues/13
