### ISSUE TITLE
Improve the dbt documenation for `ccao.corner_lot`

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#280]
Add a more in-depth description of the corner lots algorithm to the table description (`dbt\models\ccao\docs.md`) and corner lot indicator column description (`dbt\models\shared_columns.md`).

**Comment by dfsnow** [comment]
Pinging @Damonamajor on this. Good thing to knock out if you ever have down time.

**Comment by dfsnow** [comment]
Closed by #536.
