### ISSUE TITLE
Investigate new `asmt_all.tot30` field

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#307]
We are not sure what this field represents, but it's new this year and seems to be related to homeowner improvement exemptions. It may be the improvement value as calculated from a cost table, but we're not sure. Let's do some exploratory data analysis to figure out what it looks like and document it in dbt.

**Comment by Damonamajor** [comment]
For taxyr 2023, there's a max of 7,500
![image](https://github.com/ccao-data/data-architecture/assets/56321109/e3ffd168-3361-4e9d-9f95-4f5cd880cf2e)

**Comment by Damonamajor** [comment]
Step 1: does dweldat change when tot30 > 0.
Step 2: Is there a valuation change reflected in assessment all.

**Comment by wrridgeway** [comment]
According to Mirella, this is `HIE AV amount `
