### ISSUE TITLE
Consider using `iasworld.legdat.xcoord`/`ycoord` for parcel centroid location

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#352]
Unbeknownst to us, parcel centroids are in legdat, in EPSG:3435.

**Comment by wrridgeway** [comment]
```
select taxyr, count(*) AS num_nulls
from iasworld.legdat
where xcoord is null group by taxyr
order by taxyr desc
```

taxyr | num_nulls
-- | --
2024 | 5,200
2023 | 5,143
2022 | 5,211
2021 | 3,231
2020 | 1,864,035
2019 | 1,864,102
2018 | 1,864,590
2017 | 1,864,621
2016 | 1,863,996
2015 | 1,862,756
2014 | 1,862,170
2013 | 1,861,935
2012 | 1,862,181
2011 | 1,861,008
2010 | 1,859,244
2009 | 1,849,650
2008 | 1,832,618
2007 | 1,804,219
2006 | 1,771,314
2005 | 1,740,965
2004 | 1,716,218
2003 | 1,693,153
2002 | 1,673,735
2001 | 1,655,398
2000 | 1,637,269
1999 | 1,620,990

**Comment by dfsnow** [comment]
Considering that the parcel-file-based coordinates imputed by us go back farther than 2021 AND most of the differences between files are less than a couple hundred feet, I'm inclined to leave things as they are. @wrridgeway what do you think? If we're agreed then we can close this IMO.

**Comment by wrridgeway** [comment]
I'm in agreement. This will be really helpful for one-offs, but the gain from switching over completely seems minimal.
