### ISSUE TITLE
Decompose reporting views/ctas and implement dbt tests

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#366]
Some of the reporting views and CTAS are rather unwieldy - let's decompose their CTEs into views that can be tested using dbt. Other views can be refactored using views from our default athena database to decrease the amount of code used.

***Views/CTAS to decompose:***
reporting.res_report_summary
reporting.ratio_stats

***Views/CTAS to refactor:***
reporting.vw_assessment_roll
reporting.vw_top_5

**Comment by dfsnow** [comment]
Let's try to break these into testable, re-usable pieces like you did for the shared model input view.
