### ISSUE TITLE
Add dbt testing framework for seeds

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#376]
> What do we think about adding some tests to this model? In particular, I'm thinking about how the join conditions in this PR depend on the assumption that the combination of `township_code_coverage` values for final models in a given year cover all triads in that year's township. I'm not 100% confident that our current strategy for testing changed and added models would work for seeds -- we know that models will get tested if the queries that comprise them change, but I'm not sure if we can expect the same behavior for seeds whose data change -- but if we could get it working I think it would be a helpful safeguard for future maintainers who need to modify the `model.final_model.csv` seed file.
>
> Just an idea for the future, we can do this investigation in a follow-up issue!
>
_Originally posted by @jeancochrane in https://github.com/ccao-data/data-architecture/pull/365#discussion_r1559679508_

**Comment by Damonamajor** [comment]
1. Define a simple test on a seed.
2. Modify the seed data and see if the dbt test command that we run on CI, will run the tests on the modified seed.
3. else
              echo "Running tests on modified/new resources only"
              dbt test -s state:modified state:new --exclude "tag:test_qc*" --defer --state "target"
  This is hopefully going to run for modified seeds, but we're not sure.
