### ISSUE TITLE
Simplify, update, and de-duplicate condo characteristics view

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#38]
A couple (2) duplicates have made there way back into this view as it's gotten larger and more complicated. It also includes PINs it shouldn't (namely those that have been deactivated).

**Comment by dfsnow** [comment]
@wrridgeway Is this already done via one of the recent PRs?

**Comment by wrridgeway** [comment]
This is currently blocked: waiting for Mirella to investigate some discrepancies I found b/w pardat and oby for 299s

**Comment by wrridgeway** [comment]
Gonna re-open this with a new branch. Too much has changed on master since this branch was created.
