### ISSUE TITLE
Add a test to dweldat to make sure `yrblt` matches the class code

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#398]
In #377, we added a set of tests to `iasworld.dweldat.sfla` to confirm that a card's building square footage matches the square footage in its [class definition](https://github.com/ccao-data/wiki/blob/master/Data/Class-Definitions.pdf). These class definitions also include restrictions on building age, so we should add a similar set of tests to the `yrblt` column to make sure that the building age matches the class definition.

For an example of this kind of test, see `iasworld_dweldat_sfla_between_1_and_999_for_class_202`.

**Comment by Damonamajor** [comment]
@jeancochrane @dfsnow 
Is there a minimum year that we use in our tests? Having it set to a determined amount does seem useful, since there may be dates like 199 instead of 1999.

**Comment by dfsnow** [comment]
Looks like it's 1850: https://github.com/ccao-data/data-architecture/blob/47f9de181b09b23207ed6bbb917d7b88802c23d8/dbt/models/iasworld/schema/iasworld.dweldat.yml#L1512
