### ISSUE TITLE
Ingest CSDS travel time matrices

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#4]
The UChicago Center for Spatial Data Science (CSDS) has created a new set of national tract-to-tract travel time matrices for different modes of transit. We should ingest these and then potentially replace some of our "distance to X" features with actual travel times. Long-term, exploratory project, no rush. Ask @dfsnow for the link to the files.

**Comment by dfsnow** [comment]
Closing this actually, as the effort to impact ratio is pretty off on this one.
