### ISSUE TITLE
Add a "proximity to stadium" feature

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#468]
Property very close to Wrigley and other stadiums may be more expensive than property slightly farther away. As such, we should add a new feature to the model that captures the distance (in feet) to major arenas/stadiums, including:

- Wrigley Field
- United Center
- Soldier Field
- Guaranteed Rate Field
- Wintrust Arena
- UIC Pavilion

**Comment by Damonamajor** [comment]
PINS: Wrigley - 14-20-227-002-0000
United Center- 17182010350000
Soldier Field - 17221100020000
Guaranteed Rate Field - 17334000490000
Wintrust Arena - 17223210220000
UIC Pavilion - 17172390220000
