### ISSUE TITLE
Identify leasehold properties and update views

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#511]
Similar to #424, we want to identify and report on leasehold properties tracked by the CCAO. The Data Department hasn't touched these before, so I have _no idea_ where to start. My best guess would be reaching out to the Legal folks. They may know who's actually tracking these.

@ccao-jardine FYI

**Comment by wrridgeway** [comment]
Achieved [here](https://github.com/ccao-data/data-architecture/pull/591).
