### ISSUE TITLE
Add QC test for exempt parcels that have AV

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#519]
Exempt parcels should not have AV. This is a bit complicated, because parcels may or may not be exempt at different stages. Still, we should scope it out and see if a test is possible.

**Comment by wrridgeway** [comment]
@jeancochrane do we want this to only look at the most recent year of values?  There's actually a reporting view that makes this pretty easy if I'm understanding correctly:

```
select count(*)
from reporting.vw_pin_value_long
where class = 'EX'
    and tot > 0
```

**Comment by jeancochrane** [comment]
I'm not sure where the complexity comes from @wrridgeway, but it's probably worth checking with Nicole and Dan! They have more context into this issue.

**Comment by wrridgeway** [comment]
@dfsnow @ccao-jardine i summon you

**Comment by dfsnow** [comment]
@wrridgeway I think that simple test using the reporting view makes sense. Make a PR for it and tag it as a QC test like the ones for `iasworld` tables for now.
