### ISSUE TITLE
Assessment status tracker: expand geo types, and remove per major class

### ISSUE THREAD

**Issue by ccao-jardine** [ccao-data/data-architecture#545]
`pct_pin_w_value_in_group` in `reporting.vw_assessment_roll_muni` is so useful! It lets us know whether we can reasonably report on the tax base in a given municipality yet, or whether, because of the way the assessment schedule divides up some municipalities, we shouldn't yet. 

It's so useful that in addition to [detaching it](https://github.com/ccao-data/data-architecture/issues/541) and making it its own view, I'd like two more changes:

1. Let's expand the geo types and geo ids. Specifically, let's now include Chicago Ward, and to include all school districts that are property tax agencies. To accommodate this requires adding geo type and geo id columns. 
2. Currently `pct_pin_w_value_in_group` is currently unique per municipality, year, stage, and major class, as originally specified. I believe that for our new use case, it only needs to be unique per geo id, year, and stage -- removing the major class. 

The above changes do not affect any existing public reporting assets.

**Comment by wrridgeway** [comment]
See https://github.com/ccao-data/data-architecture/pull/551
