### ISSUE TITLE
Investigate duplicates in `model.vw_card_res_input`

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#558]
I had @Damonamajor add dbt tests for our modeling views to detect non-unique rows. There are currently 19 pin/card/year combos in `model.vw_card_res_input` with more than 1 row. This shouldn't be the case. My preliminary investigation suggests the nearest neighbor joins in the script for the view are creating the dupes:

```
FROM forward_fill AS f1
LEFT JOIN (
    SELECT *
    FROM forward_fill
    WHERE NOT ind_pin_is_multicard
        AND nearest_neighbor_1_dist_ft <= 500
) AS nn1
    ON f1.nearest_neighbor_1_pin10 = nn1.meta_pin10
    AND f1.meta_year = nn1.meta_year
LEFT JOIN (
    SELECT *
    FROM forward_fill
    WHERE NOT ind_pin_is_multicard
        AND nearest_neighbor_2_dist_ft <= 500
) AS nn2
    ON f1.nearest_neighbor_1_pin10 = nn2.meta_pin10
    AND f1.meta_year = nn2.meta_year
```

**Comment by wrridgeway** [comment]
@dfsnow let me know if this is a lark

**Comment by wrridgeway** [comment]
lol:

meta_pin | meta_class | meta_year | nearest_neighbor_1_pin10
-- | -- | -- | --
14201150381001 | 208 | 2017 | 1420115028
14201150280000 | 206 | 2017 | 1420115038
14201150381002 | 208 | 2017 | 1420115028

got some 208s that aren't unique by pin10

**Comment by dfsnow** [comment]
Hmmmm, I'm guessing it's a join issue. Can you trace it and maybe walk @Damonamajor through how to do so.

**Comment by wrridgeway** [comment]
I believe it's an issue with not all res parcels being unique by pin10 and doing the NN join on pin10. Take `1432413072` for example:

```
select meta_pin, meta_year, meta_class
from model.vw_card_res_input
where meta_pin10 = '1432413072' and year = '2017'
```

meta_pin | meta_year | meta_class
-- | -- | --
14324130721003 | 2017 | 278
14324130721002 | 2017 | 278
14324130721001 | 2017 | 278
