### ISSUE TITLE
Move Python dependency lists from disparate requirements files into `pyproject.toml`

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#569]
Adapted from [this comment](https://github.com/ccao-data/data-architecture/pull/568/files#r1714239019):

> It may be worth consolidating these requirements files into the project root pyproject.toml. Then we could just `pip install .[transform_dbt_test_results]`.

We should do this for all of the requirements files currently stored in this repo:

* `dbt/requirements.txt`
* `dbt/scripts/requirements.export_models.txt`
* `dbt/scripts/requirements.transform_dbt_test_results.txt`
* `etl/requirements.txt`
    * This one seems like it may have some extraneous dependencies; I suspect it may have been added based on a bare `pip freeze`. We should investigate its history and see if we can simplify it at all before adding it to `pyproject.toml`.

**Comment by dfsnow** [comment]
This was finished by #635.
