### ISSUE TITLE
Assist: properties that most impact each school district's property taxes

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#627]
## Goal: 
Produce a flat file of a list that identifies, per school taxing district in 2023, the top 10 most impactful PINs (i.e., the PINs with the largest AV). 

## Context:
There are two related [Strategic Plan initiatives](https://prodassets.cookcountyassessor.com/s3fs-public/form_documents/FINAL-2024%20Strategic%20Plan%20slides%20(external_shareable).pdf) we can assist with: "Build support amongst taxing bodies to defend quality of assessments and intervene in appeals processes" and "Evaluate opportunities for the Assessor's Office to defend our values in the Board of Review appeals process". A list of top 10 most impactful properties might help these initiatives. 

## Universe:
Please identify school districts using the `tax` database; specifically, use all agencies in `tax.agency_info`, where `major_type = SCHOOL`. Each agency has an `agency_num`, which is associated with multiple taxcodes in `tax.tax_code`. Taxcode is how PINs are associated with agencies; specifically, each PIN in `tax.pin` has one `taxcode` per year, so you can get the PINs for each agency by associating all PINs with the `taxcodes` for that agency. 

For this first attempt, please identify the top PINs by the ones with the highest 2023 CCAO Mailed AV. 

## Data requested: 
I'd like one row per PIN school district in 2023, such that each school district has 10 rows for the top 10 PINs. Columns:

- [x] agency name
- [x] agency_num
- [x] PIN rank (1 through 10)
- [x] PIN number
- [x] PIN class
- [x] PIN AV: CCAO mailed
- [x] PIN AV: CCAO final
- [x] PIN AV: BOR final
- [x] nice to have: EAV
- [x] 2023 tax bill
- [x] taxcode cumulative rate
- [x] TIF district name, to know whether the PIN is in a TIF
- [x] SSA name, to know whether the PIN is in an SSA

Other ideas?

**Comment by wrridgeway** [comment]
QUESTION: do we want to define impactful as the largest AV, or the largest bill

**Comment by ccao-jardine** [comment]
Ooh, great question. Let's go with AV
