### ISSUE TITLE
Add dbt data integrity tests to the `model` database tables

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#673]
Last week @jeancochrane found a duplicate PIN in one of our `model` tables (I believe `model.assessment_pin`). I'm not sure how that snuck in there, but we should take steps to catch such issues in the future.

Let's add [dbt data integrity tests](https://github.com/ccao-data/data-architecture/tree/master/dbt#data-integrity-tests) to each of the `model` database sources. We can trigger the tests as part of the weekly cron job and/or via an API call after the completion of a model run (similar to the one called via [service-spark-iasworld](https://github.com/ccao-data/service-spark-iasworld/blob/main/src/utils/github.py)). We'll mostly want to test for null values and uniqueness.

**Comment by Damonamajor** [comment]
https://us-east-1.console.aws.amazon.com/s3/buckets/ccao-model-results-us-east-1?region=us-east-1&bucketType=general&prefix=feature_importance/year%3D2024/&showversions=false

feature importance is duplicated for 2024-02-05-sad-tristan.parquet
