### ISSUE TITLE
[Data catalog] dbt CI is not properly selecting for new and modified models

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#68]
I noticed that the [most recent CI run](https://github.com/ccao-data/data-architecture/actions/runs/5857518680/job/15879535306) for the `data-catalog` branch did not (re)build any of the models we added or changed in https://github.com/ccao-data/data-architecture/pull/64. Testing things out locally, I noticed two problems:

1. We're missing the `state:new` selector in our workflow configuration, which is intended to select for new models
2. In my local environment, neither `state:new` nor `state:modified` properly picks up additions or changes to the model definition

**Comment by dfsnow** [comment]
Closing manually since for some reason #69 did not close this on merge.
