### ISSUE TITLE
Remove deactivated rows from appeal view

### ISSUE THREAD

**Issue by wrridgeway** [ccao-data/data-architecture#73]
Some tables in iasWorld contain rows that have been deactivated - these rows should not be used for anything by Data, they are maintained in iasWorld purely for historical purposes. As of now, I only know of three tables where we need to be wary of removing deactivated rows - htpar, land, and asmt_all. I've added the conditional WHERE deactivat IS NULL where necessary.

**Comment by wrridgeway** [comment]
Some tables in iasWorld contain rows that have been deactivated - these rows should not be used for anything by data, they are maintained in iasWorld purely for historical purposes. As of now, I only know of three tables where we need to be wary of removing deactivated rows - htpar, land, and asmt_all. I've added the conditional `WHERE deactivat IS NULL` where necessary.

**Comment by dfsnow** [comment]
Closed by #55.
