### ISSUE TITLE
[Data catalog] Add tests for the reporting views

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#95]
See the "reporting" tab of [sql_guide.xlsx](https://cookcounty-my.sharepoint.com/:x:/g/personal/william_ridgeway_cookcountyil_gov/EfSAPa4UHGBDoxCsIpNjNX8BOiQ-YdAKvt4Bf9wf5sNrWg?e=n2lEug).

In cases where there are values in the "assumptions" or "nuances" columns, add this info to the corresponding `docs.md` block for that view. For an example, see some of the existing documentation:

https://github.com/ccao-data/data-architecture/blob/ca704e5a8a2f5e09527c34e75e40f4991748f038/dbt/models/default/docs.md?plain=1#L47-L72

**Comment by wrridgeway** [comment]
Let's go with checking that each PIN only appears once in the view
